// Generates lib/data/thirdsAllocation.ts from the official FIFA third-place
// allocation table published on Wikipedia (Annex C of the tournament regulations).
//
// The 2026 World Cup has 12 groups; the 8 best third-placed teams advance. Which
// group's third-placed team is sent to which Round-of-32 match depends on the exact
// set of 8 groups that produced a qualifying third — there are C(12,8) = 495 such
// combinations, each with a fixed assignment. This script fetches that table and
// emits a lookup keyed by the sorted qualifying-group letters.
//
// Run: node scripts/buildThirdsAllocation.mjs
// Requires network access (Node 18+ global fetch).

import { writeFileSync } from 'node:fs'

const API = 'https://en.wikipedia.org/w/api.php?action=parse&page=Template:2026_FIFA_World_Cup_third-place_table&prop=wikitext&format=json'
const LETTERS = [...'ABCDEFGHIJKL']
// Assignment columns in the source table, in order: 1A,1B,1D,1E,1G,1I,1K,1L.
// These map to the eight Round-of-32 matches that face a third-placed team.
const COL_TO_MATCH = [79, 85, 82, 75, 81, 78, 88, 80]

const res = await fetch(API, { headers: { 'User-Agent': 'simulador-mundial-2026/1.0' } })
const json = await res.json()
const wt = json.parse.wikitext['*']

const parts = wt.split(/!\s*scope="row"\s*\|\s*(\d+)/)
/** @type {Record<string, Record<number,string>>} */
const out = {}
for (let i = 1; i < parts.length; i += 2) {
  const block = parts[i + 1]
  const cells = []
  for (const line of block.split('\n')) {
    const s = line.trim()
    if (s.startsWith('|') && !s.startsWith('|-') && !s.startsWith('|+') && !s.startsWith('|}')) {
      for (const tok of s.slice(1).split('||')) cells.push(tok.replaceAll("'''", '').trim())
    }
  }
  const cs = cells.slice(0, 20)
  if (cs.length !== 20) throw new Error(`row ${parts[i]}: expected 20 cells, got ${cs.length}`)
  const groups = cs.slice(0, 12)
  const assign = cs.slice(12, 20)
  const qualifying = LETTERS.filter((_, k) => groups[k] !== '')
  if (qualifying.length !== 8) throw new Error(`row ${parts[i]}: ${qualifying.length} qualifying groups`)
  const map = {}
  assign.forEach((cell, j) => { map[COL_TO_MATCH[j]] = cell.replace('3', '') })
  out[[...qualifying].sort().join('')] = map
}

const n = Object.keys(out).length
if (n !== 495) throw new Error(`expected 495 combinations, got ${n}`)

const body = Object.entries(out)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, m]) => {
    const inner = COL_TO_MATCH.slice().sort((a, b) => a - b).map((mn) => `${mn}:'${m[mn]}'`).join(',')
    return `  '${key}':{${inner}},`
  })
  .join('\n')

const file = `// AUTO-GENERATED by scripts/buildThirdsAllocation.mjs — do not edit by hand.
// Official FIFA 2026 third-place allocation: ${n} combinations of 8 qualifying groups.
// Key = sorted qualifying group letters. Value = { R32 match number -> source group }.
import { GroupId } from '@/lib/types'

export const THIRDS_ALLOCATION: Record<string, Record<number, GroupId>> = {
${body}
}
`
writeFileSync(new URL('../lib/data/thirdsAllocation.ts', import.meta.url), file)
console.log(`Wrote lib/data/thirdsAllocation.ts with ${n} combinations.`)
