// Generates lib/data/schedule.ts: the real group-stage calendar (with kickoff
// times) of the 2026 World Cup, from openfootball. Each kickoff is stored as an
// absolute UTC ISO timestamp so the UI can render/sort it in any timezone
// (e.g. Europe/Madrid).
//
// Run: node scripts/buildSchedule.mjs   (requires network, Node 18+)

import { writeFileSync } from 'node:fs'

const SRC_URL = 'https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json'

// openfootball name -> our team id (group teams only)
const NAME_TO_ID = {
  Mexico: 'MEX', 'South Africa': 'RSA', 'South Korea': 'KOR', 'Czech Republic': 'CZE',
  Canada: 'CAN', Switzerland: 'SUI', Qatar: 'QAT', 'Bosnia & Herzegovina': 'BIH',
  Brazil: 'BRA', Morocco: 'MAR', Scotland: 'SCO', Haiti: 'HAI',
  USA: 'USA', Australia: 'AUS', Paraguay: 'PAR', Turkey: 'TUR',
  Germany: 'GER', Ecuador: 'ECU', 'Ivory Coast': 'CIV', 'Curaçao': 'CUW',
  Netherlands: 'NED', Japan: 'JPN', Tunisia: 'TUN', Sweden: 'SWE',
  Belgium: 'BEL', Iran: 'IRN', Egypt: 'EGY', 'New Zealand': 'NZL',
  Spain: 'ESP', Uruguay: 'URU', 'Saudi Arabia': 'KSA', 'Cape Verde': 'CPV',
  France: 'FRA', Senegal: 'SEN', Norway: 'NOR', Iraq: 'IRQ',
  Argentina: 'ARG', Austria: 'AUT', Algeria: 'ALG', Jordan: 'JOR',
  Portugal: 'POR', Colombia: 'COL', Uzbekistan: 'UZB', 'DR Congo': 'COD',
  England: 'ENG', Croatia: 'CRO', Panama: 'PAN', Ghana: 'GHA',
}

// "YYYY-MM-DD" + "HH:MM UTC-6" -> absolute UTC ISO string.
function toUtcIso(date, time) {
  const m = time.match(/^(\d{1,2}):(\d{2})\s*UTC([+-]\d{1,2})$/)
  if (!m) return null
  const [, hh, mm, off] = m
  const [y, mo, d] = date.split('-').map(Number)
  // local = UTC + offset  =>  UTC = local - offset
  const utcMs = Date.UTC(y, mo - 1, d, Number(hh) - Number(off), Number(mm))
  return new Date(utcMs).toISOString()
}

const res = await fetch(SRC_URL, { headers: { 'User-Agent': 'simulador-mundial-2026/1.0' } })
const data = await res.json()

const rows = []
for (const m of data.matches) {
  const gm = (m.group || '').match(/^Group ([A-L])$/)
  if (!gm) continue
  const home = NAME_TO_ID[m.team1]
  const away = NAME_TO_ID[m.team2]
  const kickoff = toUtcIso(m.date, m.time || '')
  if (!home || !away || !kickoff) throw new Error(`bad group match: ${JSON.stringify(m)}`)
  rows.push({ group: gm[1], home, away, date: m.date, kickoff })
}
if (rows.length !== 72) throw new Error(`expected 72 group matches, got ${rows.length}`)
rows.sort((a, b) => (a.kickoff < b.kickoff ? -1 : a.kickoff > b.kickoff ? 1 : a.group.localeCompare(b.group)))

const body = rows
  .map((r) => `  { group: '${r.group}', home: '${r.home}', away: '${r.away}', date: '${r.date}', kickoff: '${r.kickoff}' },`)
  .join('\n')

const file = `// AUTO-GENERATED by scripts/buildSchedule.mjs — do not edit by hand.
// Real 2026 World Cup group-stage calendar (source: openfootball). \`kickoff\` is
// an absolute UTC ISO timestamp; render it in any timezone (e.g. Europe/Madrid).
import { GroupId } from '@/lib/types'

export interface ScheduledMatch {
  group: GroupId
  home: string
  away: string
  date: string // local match date 'YYYY-MM-DD'
  kickoff: string // absolute UTC ISO
}

export const GROUP_SCHEDULE: ScheduledMatch[] = [
${body}
]
`
writeFileSync(new URL('../lib/data/schedule.ts', import.meta.url), file)
console.log(`Wrote lib/data/schedule.ts with ${rows.length} group matches.`)
