// Genera lib/data/comparadorData.ts con forma reciente y head-to-head de las
// 48 selecciones del Mundial 2026, a partir del dataset abierto martj42.
// Ejecutar: node scripts/buildComparadorData.mjs   (requiere red)
import { writeFileSync } from 'node:fs'

const CSV_URL = 'https://raw.githubusercontent.com/martj42/international_results/master/results.csv'

// Nombre del dataset (inglés) -> id interno. Incluye alias conocidos.
const NAME_TO_ID = {
  Mexico: 'MEX', 'South Korea': 'KOR', 'South Africa': 'RSA', 'Czech Republic': 'CZE', Czechia: 'CZE',
  Canada: 'CAN', Switzerland: 'SUI', Qatar: 'QAT', 'Bosnia and Herzegovina': 'BIH',
  Brazil: 'BRA', Morocco: 'MAR', Scotland: 'SCO', Haiti: 'HAI',
  'United States': 'USA', Australia: 'AUS', Paraguay: 'PAR', Turkey: 'TUR', 'Türkiye': 'TUR',
  Germany: 'GER', Ecuador: 'ECU', 'Ivory Coast': 'CIV', 'Curaçao': 'CUW', Curacao: 'CUW',
  Netherlands: 'NED', Japan: 'JPN', Tunisia: 'TUN', Sweden: 'SWE',
  Belgium: 'BEL', Iran: 'IRN', Egypt: 'EGY', 'New Zealand': 'NZL',
  Spain: 'ESP', Uruguay: 'URU', 'Saudi Arabia': 'KSA', 'Cape Verde': 'CPV', 'Cabo Verde': 'CPV',
  France: 'FRA', Senegal: 'SEN', Norway: 'NOR', Iraq: 'IRQ',
  Argentina: 'ARG', Austria: 'AUT', Algeria: 'ALG', Jordan: 'JOR',
  Portugal: 'POR', Colombia: 'COL', Uzbekistan: 'UZB', 'DR Congo': 'COD', 'Congo DR': 'COD',
  England: 'ENG', Croatia: 'CRO', Panama: 'PAN', Ghana: 'GHA',
}
const OUR = new Set(Object.values(NAME_TO_ID))

// Parser CSV mínimo que respeta comillas dobles.
function parseLine(line) {
  const out = []
  let cur = '', q = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (q) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++ }
      else if (c === '"') q = false
      else cur += c
    } else if (c === '"') q = true
    else if (c === ',') { out.push(cur); cur = '' }
    else cur += c
  }
  out.push(cur)
  return out
}

const text = await (await fetch(CSV_URL)).text()
const lines = text.split('\n').filter((l) => l.trim().length > 0)
const header = parseLine(lines[0])
const col = (name) => header.indexOf(name)
const iDate = col('date'), iH = col('home_team'), iA = col('away_team'), iHG = col('home_score'), iAG = col('away_score')

const matches = []
for (let i = 1; i < lines.length; i++) {
  const f = parseLine(lines[i])
  const hg = Number(f[iHG]), ag = Number(f[iAG])
  if (!Number.isFinite(hg) || !Number.isFinite(ag) || f[iHG] === '' || f[iAG] === '') continue
  matches.push({ date: f[iDate], home: f[iH], away: f[iA], hg, ag })
}
matches.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
const snapshot = matches.length ? matches[matches.length - 1].date : ''

// FORM: últimos 5 por selección.
const formByTeam = {}
const pushForm = (id, oppName, oppId, gf, ga, date) => {
  const res = gf > ga ? 'W' : gf < ga ? 'L' : 'D'
  ;(formByTeam[id] ??= []).push({ date, oppName, oppId, gf, ga, res })
}
for (const m of matches) {
  const idH = NAME_TO_ID[m.home], idA = NAME_TO_ID[m.away]
  if (idH) pushForm(idH, m.away, idA ?? null, m.hg, m.ag, m.date)
  if (idA) pushForm(idA, m.home, idH ?? null, m.ag, m.hg, m.date)
}
const FORM = {}
for (const id of Object.keys(formByTeam)) {
  FORM[id] = formByTeam[id].slice(-5).reverse() // más reciente primero
}

// H2H: pares de nuestras 48 que se han enfrentado.
const h2h = {}
for (const m of matches) {
  const idH = NAME_TO_ID[m.home], idA = NAME_TO_ID[m.away]
  if (!idH || !idA || idH === idA) continue
  const [lo, hi] = idH < idA ? [idH, idA] : [idA, idH]
  const key = `${lo}|${hi}`
  const rec = (h2h[key] ??= { played: 0, winsLo: 0, draws: 0, winsHi: 0, all: [] })
  rec.played++
  const loGoals = idH === lo ? m.hg : m.ag
  const hiGoals = idH === lo ? m.ag : m.hg
  if (loGoals > hiGoals) rec.winsLo++
  else if (loGoals < hiGoals) rec.winsHi++
  else rec.draws++
  rec.all.push({ date: m.date, loId: lo, hiId: hi, loGoals, hiGoals })
}
const H2H = {}
for (const key of Object.keys(h2h)) {
  const r = h2h[key]
  H2H[key] = { played: r.played, winsLo: r.winsLo, draws: r.draws, winsHi: r.winsHi, last: r.all.slice(-3).reverse() }
}

// Aviso: selecciones nuestras sin forma (posible fallo de mapeo).
for (const id of OUR) if (!FORM[id]) console.warn(`[buildComparadorData] sin forma para ${id} (¿mapeo de nombre?)`)

const out = `// AUTO-GENERATED by scripts/buildComparadorData.mjs — no editar a mano.
export const SNAPSHOT_DATE = ${JSON.stringify(snapshot)}

export interface H2HMeeting { date: string; loId: string; hiId: string; loGoals: number; hiGoals: number }
export interface H2HRecord { played: number; winsLo: number; draws: number; winsHi: number; last: H2HMeeting[] }
export const H2H: Record<string, H2HRecord> = ${JSON.stringify(H2H)}

export interface FormMatch { date: string; oppName: string; oppId: string | null; gf: number; ga: number; res: 'W' | 'D' | 'L' }
export const FORM: Record<string, FormMatch[]> = ${JSON.stringify(FORM)}
`
writeFileSync(new URL('../lib/data/comparadorData.ts', import.meta.url), out)
console.log(`OK — ${Object.keys(FORM).length} selecciones con forma, ${Object.keys(H2H).length} pares h2h, snapshot ${snapshot}`)
